[package]
name = "do_todo"
version = "0.1.0-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
crossterm = "0.26"
dirs = "4.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
tui = { package = "ratatui", version = "0.20.1", features = ["serde"]}
tui-textarea = { git = "https://github.com/rhysd/tui-textarea", features = ["ratatui-crossterm"], default-features=false }
itertools = "0.10.5"
lazy_static = "1.4.0"


# Using textwrap for now until tui-rs implements more general wrapping for widgets such as Tables.
# This somewhat limits styling capabilities, as the wrapping is applied to strings, not tui::text::Text
# However it should be fine with the current use case
unicode-segmentation = "1.10.0"

textwrap = { version = "0.15" }


[[bin]]
bench = false
name = "dotodo"
path = "src/main.rs"
