[package]
name = "do_todo"
version = "0.1.0-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.17"
crossterm = "0.22"
chrono = "0.4"

[[bin]]
bench = false
name = "dotodo"
path = "src/main.rs"
