[package]
name = "do_todo"
version = "0.1.0-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
crossterm = "0.22"
dirs = "4.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
tui = { version = "0.17", features = ["serde"] }

[[bin]]
bench = false
name = "dotodo"
path = "src/main.rs"
