name: Continuous Deployment

on:
  push:
    tags:
    - "*"
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    env:
      UPLOAD_URL: ${{ steps.create-release-draft.outputs.upload_url }}
    steps:
      - name: Create release draft
        id: create-release-draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dist:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            build: windows-x86_64
            friendly_name: windows
          - os: macos-latest
            build: x86_64-apple-darwin
            friendly_name: macos
          - os: ubuntu-latest
            build: linux-x86_64
            friendly_name: linux
    runs-on: ${{ matrix.os }}
    needs: create-release
    name: Releases to ${{ matrix.friendly_name }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          staging="tododo_${{ matrix.build }}"
          mkdir -p "$staging"
          cargo build --verbose --release
          if [ "${{matrix.os}}" = "windows-latest"]; then
            cp target/release/tododo.exe "$staging/"
            7z a "$staging.zip" "$staging"
            echo "ASSET=$staging.zip" >> $GITHUB_ENV
          else
            cp target/release/tododo "$staging/"
            tar czf "$staging.tar.gz" "$staging"
            echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
          fi
      - name: Upload
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ${{ env.ASSET }}
          asset_name: ${{ env.ASSET }}
          asset_content_type: application/octet-stream 
