name: Continuous Deployment

on:
  push:
    tags:
    - "*"
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload-url: ${{ steps.create-release-draft.outputs.upload_url }}
    steps:
      - name: Create release draft
        id: create-release-draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dist-linux:
    name: Releases to linux
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Upload
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload-url }}
        asset_path: ./target/release/too_many_emails
        asset_name: too-many-emails-linux
        asset_content_type: binary/octet-stream

  dist-windows:
    name: Releases to windows
    runs-on: windows-latest
    needs: create-release
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Upload
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload-url }}
        asset_path: ./target/release/too_many_emails.exe
        asset_name: too-many-emails-windows.exe
        asset_content_type: binary/octet-stream

  dist-macos:
    name: Releases to macOS
    runs-on: macOS-latest
    needs: create-release
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Upload
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload-url }}
        asset_path: ./target/release/too_many_emails
        asset_name: too-many-emails-macos
        asset_content_type: binary/octet-stream
