name: windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    name: Tests windows
    strategy:
      matrix:
        release_channel: [nightly,stable]

    steps:
    - uses: actions/checkout@v2
    - name: Install rustup
      run: 
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
        sh rustup.sh -y --default-toolchain ${{ matrix.release_channel }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
