name: linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Runs linter

    steps:
    - uses: actions/checkout@v2
    - name: Install rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
        sh rustup.sh -y --default-toolchain stable
        rustup update
        rustup component add clippy
        rustup component add rustfmt
    - name: Build
      run: cargo build --verbose
    - name: Run linter
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
